// GENERATED by export_flow_header.py; do not edit model constants.
// Source SHA256: 7466fcd0cfcebae27690419572508d461fd61b9bc4ad21ec0de5d8edc46af93f
#ifndef FLOW_MODEL_H
#define FLOW_MODEL_H
#include <cmath>
#include <cstdint>
#include <limits>
namespace flow_model {
static const char MODEL_VERSION[] = "flow-knn-2";
static const int REFERENCE_COUNT = 180;
static const int K = 3;
static const int WINDOW = 5;
static const double INTERVAL_SECONDS = 20.0;
static const double TOLERANCE_SECONDS = 2.0;
static const double STALE_SECONDS = 45.0;
static const double MIN_VALID_FLOW = 0.5;
static const double MAX_VALID_FLOW = 15.0;
static const double MIN_INLET_FLOW = 8.0;
static const double MAX_INLET_FLOW = 12.0;
static const float MEANS[4] = {1.2308917f, 8.97095924e-06f, 0.304186016f, 1.63990796f};
static const float SCALES[4] = {1.6072042f, 0.033309944f, 0.869894683f, 2.03915071f};
static const float REFERENCES[REFERENCE_COUNT][4] = {
  {-0.75233233f, 0.120866343f, -0.327038437f, -0.730927706f},
  {-0.998788238f, -7.41374874f, 4.18038511f, 1.33661985f},
  {-0.896645069f, -0.802540302f, -0.221217901f, -0.850628436f},
  {-0.612646282f, 0.245679721f, -0.343020141f, -0.717900813f},
  {-0.633729517f, 0.537401855f, -0.325602144f, -0.836353004f},
  {-1.07852483f, 0.461342573f, -0.223916456f, -1.09950566f},
  {-0.86969763f, 0.036661841f, -0.27668041f, -0.834922254f},
  {-0.916743934f, -0.342670888f, -0.270787835f, -0.735712826f},
  {-0.848924935f, 0.208496869f, -0.199178606f, -0.773477495f},
  {-0.732751131f, -0.113466181f, -0.31960234f, -0.816338181f},
  {-0.961987078f, -0.351858705f, -0.302055895f, -0.926537693f},
  {-0.798192739f, -0.119112715f, -0.323766112f, -0.855468869f},
  {-0.481456995f, 0.118695065f, -0.245925665f, -0.747463822f},
  {-0.915355802f, -0.371300101f, -0.264062703f, -0.733848929f},
  {-0.721212447f, 0.409658581f, -0.26425758f, -0.834095776f},
  {-0.588238716f, 0.695266902f, 4.06557703f, -0.965891004f},
  {-0.702458143f, 0.0805079937f, -0.291438699f, -0.693537891f},
  {-0.55643189f, -0.313263863f, 2.53999424f, -0.521244705f},
  {-0.678185582f, -0.0206364729f, -0.341867894f, -0.742406189f},
  {-0.762553811f, 0.0616332479f, -0.265269637f, -0.707339048f},
  {-0.729288578f, -0.0785745606f, -0.3206352f, -0.853344321f},
  {-0.876959324f, -0.621725678f, -0.31979537f, -0.844165027f},
  {-0.479227662f, 0.837648749f, -0.210995823f, -0.871581316f},
  {-0.834865749f, -0.505287588f, -0.263362736f, -0.730100393f},
  {-0.774875224f, 0.0379610583f, -0.26687628f, -0.939045548f},
  {-0.893225431f, -0.178205952f, -0.321235687f, -0.835773468f},
  {-0.937662244f, -0.111075036f, -0.310973614f, -0.908893824f},
  {-0.693206668f, -0.366052657f, -0.302568197f, -0.604564786f},
  {-0.479066521f, 0.763190687f, -0.220215976f, -0.793364048f},
  {-0.884827018f, -0.709082067f, -0.277854472f, -0.741508603f},
  {-0.958775938f, -0.498132259f, -0.265012413f, -0.739823878f},
  {-0.809774935f, 0.384839505f, -0.30440715f, -0.800179541f},
  {-0.680574179f, -0.161127806f, 2.51419711f, -0.733069718f},
  {-0.569511771f, -0.127070665f, -0.303739697f, -0.622843087f},
  {-0.300494939f, 0.47436136f, -0.208937287f, -0.593508184f},
  {-0.65827024f, -0.649538517f, -0.309142977f, -0.536401272f},
  {-0.745501876f, -0.700623989f, -0.20308575f, -0.76491487f},
  {-0.897640586f, -0.128635913f, -0.310197741f, -0.888000011f},
  {-0.993172944f, -0.189095616f, -0.282015175f, -0.879250228f},
  {-0.640883505f, 0.244254783f, -0.323330432f, -0.784286559f},
  {-0.750086188f, 0.450610161f, 1.63413131f, -0.784942865f},
  {-1.01428664f, -0.665621161f, -0.303239375f, -0.999438882f},
  {-1.03450561f, -0.974771798f, -0.27411887f, -0.893125534f},
  {-0.743854284f, -0.419942707f, 0.877524972f, -0.645834029f},
  {-0.707021356f, 0.213915959f, -0.310734481f, -0.746224225f},
  {-0.798925042f, -0.173738435f, -0.324730366f, -0.875632107f},
  {-0.754147947f, -0.173133507f, -0.346871734f, -0.768936932f},
  {-0.99814117f, -0.718865693f, -0.246716931f, -0.866144001f},
  {-0.892566562f, -0.0346779563f, -0.212966666f, -0.846957982f},
  {-0.542825699f, 0.420960367f, -0.277177453f, -0.773574591f},
  {-0.705017269f, -0.0392852314f, -0.340372354f, -0.753147244f},
  {-0.953184247f, -1.51695609f, -0.197902635f, -0.732509255f},
  {-0.508890986f, 0.276610225f, -0.28151691f, -0.732754946f},
  {-0.814590156f, 0.0620420538f, -0.247187197f, -0.813402414f},
  {-0.644016325f, -0.221184865f, 4.65814209f, -0.866215646f},
  {-0.926332653f, -0.917888641f, -0.290507823f, -0.735760331f},
  {-0.821470439f, -0.22225295f, -0.110523298f, -0.771751106f},
  {-0.572343409f, 0.100155413f, -0.217431694f, -0.771661282f},
  {-0.868372381f, -0.111519925f, -0.291732937f, -0.880296409f},
  {-0.906158447f, -0.492527604f, -0.222373173f, -0.781072378f},
  {-0.17359817f, 1.28935909f, -0.214802682f, -0.45422712f},
  {-0.0983488709f, 0.436447591f, -0.293365061f, -0.241715282f},
  {0.13838084f, 0.559932232f, -0.249067605f, 0.113437183f},
  {-0.399163157f, 0.0732834786f, -0.340758294f, -0.4667328f},
  {-0.223455563f, -1.49398041f, -0.187252939f, 0.0202315897f},
  {-0.614809692f, 0.24024421f, -0.300843865f, -0.578829527f},
  {-0.193146408f, 0.0676767305f, -0.328353852f, -0.264363199f},
  {-0.233772233f, 0.436668754f, -0.324434042f, -0.328248113f},
  {-0.036425814f, 0.148032367f, -0.344309866f, -0.106617779f},
  {-0.294611424f, 0.13278535f, -0.335973114f, -0.419256508f},
  {-0.613068163f, -0.56846422f, -0.168530464f, -0.787984312f},
  {-0.47996062f, -0.178599775f, -0.278920919f, -0.323497266f},
  {-0.17765367f, -0.258177876f, -0.326592028f, -0.17240189f},
  {0.0436274856f, -0.947005332f, -0.295133978f, 0.230595395f},
  {-0.720777571f, -0.609568775f, -0.299733341f, -0.733328521f},
  {-0.137918204f, -0.289780945f, -0.334186912f, -0.0384185165f},
  {-0.311576277f, -0.22540015f, -0.304089665f, -0.263588488f},
  {0.0432000346f, 0.583118916f, -0.321159512f, -0.134237066f},
  {-0.0723938644f, 0.051644966f, -0.319740921f, -0.168278143f},
  {-0.39182061f, 0.223306969f, -0.292103171f, -0.335373253f},
  {-0.160513341f, 0.00113581738f, -0.333154202f, -0.137815073f},
  {0.32203269f, 0.516692162f, -0.273598343f, 0.166788191f},
  {-0.212688416f, -0.627142787f, 0.115365192f, -0.463784099f},
  {-0.531120241f, -0.0230279211f, -0.320652306f, -0.548974037f},
  {-0.217069313f, 0.30816856f, -0.335611254f, -0.294459343f},
  {-0.220540568f, -0.142304853f, -0.280083269f, -0.0791762844f},
  {-0.278872907f, 0.63643527f, -0.291406512f, -0.375505239f},
  {-0.235913843f, 0.511704683f, -0.255199581f, -0.246765807f},
  {-0.136209652f, 0.362792552f, -0.30769679f, -0.340685397f},
  {-0.29409188f, -0.324372023f, -0.0243206415f, -0.418005049f},
  {-0.321723104f, -0.095881097f, -0.279401541f, -0.305107534f},
  {0.343508482f, 0.0103311818f, -0.325352758f, 0.261821717f},
  {0.316654384f, -0.278019518f, -0.313329309f, 0.376119435f},
  {-0.768404961f, -1.07352018f, -0.189570054f, -0.363321006f},
  {-0.065074943f, -0.527434111f, -0.266731381f, -0.010242465f},
  {-0.335107207f, 0.218676358f, -0.336403847f, -0.43814218f},
  {-0.100008897f, -0.17826046f, -0.307744682f, 0.0620916598f},
  {-0.561220348f, -1.02227223f, -0.227188319f, -0.212166175f},
  {-0.308655679f, -0.0132365879f, -0.302302659f, -0.308663517f},
  {-0.574051976f, -0.143167585f, -0.346727908f, -0.563700795f},
  {-0.19808355f, -0.265165836f, 0.348469913f, -0.518274248f},
  {-0.29515335f, -0.204846278f, -0.319177151f, -0.293947816f},
  {0.0022842628f, 1.03494465f, -0.0548001043f, -0.216994584f},
  {-0.17623879f, 1.55825758f, -0.185082808f, -0.562194884f},
  {0.0442223065f, 0.729466319f, -0.20819056f, -0.282888383f},
  {-0.242534027f, 0.202014267f, -0.246010303f, -0.361248344f},
  {-0.538125575f, -0.372337639f, -0.174304664f, -0.437199593f},
  {-0.207180098f, 0.103793375f, -0.335576653f, -0.313394725f},
  {-0.428830832f, -0.622413814f, -0.302419633f, -0.278660685f},
  {-0.560720086f, -0.552404284f, -0.292824686f, -0.421212465f},
  {-0.742321789f, -1.09953809f, -0.279222965f, -0.504658937f},
  {0.0949215218f, 1.64658606f, 0.0266364347f, -0.518141389f},
  {-0.501611233f, -0.320382684f, -0.256855726f, -0.36322394f},
  {-0.843277216f, -0.212913126f, -0.344194442f, -0.817100942f},
  {0.0527850017f, -0.603236318f, -0.320849717f, 0.114553303f},
  {-0.563786328f, -0.0787601173f, -0.347274393f, -0.59424001f},
  {-0.396255642f, -1.22572863f, -0.00334464735f, -0.476176322f},
  {-0.334021479f, -0.278065801f, -0.311968505f, -0.354813933f},
  {-0.189853728f, 0.0573250279f, -0.330206722f, -0.175891772f},
  {-0.149481148f, 0.096044898f, -0.296745151f, -0.112915121f},
  {1.55106127f, -1.01088941f, -0.284044027f, 1.84144413f},
  {1.86453736f, 0.949775159f, -0.285416871f, 1.8365351f},
  {1.50699902f, 0.290179282f, -0.252050906f, 1.42497075f},
  {1.41820705f, -0.511128664f, 3.25533628f, 0.440578818f},
  {1.33563626f, -0.0511851236f, -0.344624549f, 1.39223278f},
  {1.93512821f, 0.908082128f, -0.30077064f, 1.8275286f},
  {2.0253396f, -0.430626512f, -0.330452681f, 2.17803073f},
  {0.633739769f, 0.195441097f, -0.262791753f, 0.821833551f},
  {1.68311608f, 0.0807136074f, -0.334082097f, 1.70670617f},
  {1.12957656f, -0.0880325437f, -0.329274565f, 1.15831602f},
  {1.78003347f, 0.146757662f, 3.71436119f, 0.581556916f},
  {2.16519785f, 0.255668014f, -0.324048579f, 2.14114046f},
  {1.6444881f, 0.199439317f, -0.317486644f, 1.72957516f},
  {1.88820767f, 0.250718117f, -0.316549838f, 1.95124257f},
  {2.13687539f, 0.22588703f, -0.32803598f, 2.07091427f},
  {1.27553558f, -1.48369932f, 3.19873071f, 0.526438951f},
  {1.21693325f, 0.187889159f, 2.80347776f, 0.549438834f},
  {1.31152546f, -0.413913935f, -0.333681732f, 1.41935444f},
  {2.783952f, -0.166761741f, -0.316697389f, 2.84578919f},
  {1.56205869f, 0.321512818f, -0.320713967f, 1.55856764f},
  {1.25140119f, -0.29965952f, -0.274497807f, 1.5393846f},
  {1.13496852f, -0.557008803f, -0.24102129f, 1.1181556f},
  {1.26651061f, -0.447237819f, -0.296754062f, 1.40022564f},
  {1.25451648f, -0.409979224f, -0.256655127f, 1.44236851f},
  {1.11704361f, -0.0854557157f, -0.278893858f, 1.0321635f},
  {1.41175663f, -0.0166487768f, -0.337549478f, 1.42918336f},
  {1.62533498f, -0.189020514f, -0.324344456f, 1.78807068f},
  {1.04100919f, 0.299995065f, 1.39700496f, 0.603987634f},
  {0.96563226f, 0.160047352f, -0.318971306f, 1.12090981f},
  {2.79608846f, 2.12166333f, 0.101624832f, 2.25421882f},
  {0.336216927f, -0.209502175f, -0.333462477f, 0.426468283f},
  {1.95550525f, -0.144348383f, -0.337585926f, 2.12094069f},
  {2.41182303f, -0.504174829f, -0.270779222f, 2.71804309f},
  {1.31456494f, -0.58452636f, 2.66742539f, 0.845116913f},
  {0.548581958f, 0.614546597f, -0.280657411f, 0.439256579f},
  {2.37329459f, 1.05976999f, -0.283496916f, 2.2419467f},
  {1.87805772f, 6.54188347f, 2.97044039f, -0.0513978787f},
  {1.63720465f, -0.161318466f, -0.294366449f, 1.85337734f},
  {1.8813746f, -0.211062416f, -0.161040917f, 1.81929171f},
  {1.10770762f, 0.0135417907f, -0.32042703f, 1.1376673f},
  {1.1401341f, -0.374818265f, -0.148142606f, 1.46625793f},
  {2.5196321f, -0.172015578f, -0.32773304f, 2.66270399f},
  {1.18339682f, -0.0406514369f, -0.287556052f, 1.30652738f},
  {1.27809596f, -0.00293894671f, -0.329573691f, 1.26907909f},
  {0.624347091f, -0.538107991f, -0.309440434f, 0.834854424f},
  {2.05783129f, 0.422551602f, -0.327228338f, 2.10654545f},
  {1.41435742f, 0.070608519f, -0.343466759f, 1.43254781f},
  {0.394803762f, 0.0125873107f, -0.222766578f, 0.459554315f},
  {1.09772062f, 0.369406968f, -0.249545544f, 1.00605297f},
  {2.36853743f, 0.681797266f, -0.325514227f, 2.3271246f},
  {1.13971281f, 0.0804896057f, -0.343823165f, 1.17156267f},
  {2.98233676f, 0.19242543f, -0.323376149f, 3.06958699f},
  {0.556143582f, 0.213874266f, -0.313375354f, 0.537098944f},
  {2.48533845f, -0.0517008752f, -0.329323351f, 2.61430407f},
  {1.34566927f, -0.512131691f, -0.324929535f, 1.5408231f},
  {1.54644275f, -0.113635518f, -0.302066147f, 1.60762751f},
  {2.55953312f, 0.76513797f, -0.286117345f, 2.63785028f},
  {0.913808763f, -0.156364933f, 1.32892346f, 1.07477367f},
  {0.222988009f, 0.332982838f, -0.340222418f, 0.137463748f},
  {2.92138362f, 0.603693247f, -0.308315575f, 2.86185837f},
};
static const std::uint8_t LABELS[REFERENCE_COUNT] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2};

// Class IDs match Python: 0 normal, 1 minor, 2 major; -1 means unavailable.
struct Prediction {
  int class_id;
  double vote_fraction;  // Neighbor agreement, NOT calibrated probability.
};

inline const char* className(int id) {
  return id == 0 ? "normal" : id == 1 ? "minor" : id == 2 ? "major" : "unavailable";
}

// Input order: delta_q, delta_q_roc, rolling_variance, cumulative_mismatch.
// Units: L/min, (L/min)/second, (L/min)^2, litres.
inline Prediction predict(const double features[4]) {
  double scaled[4];
  for (int j = 0; j < 4; ++j) {
    if (!std::isfinite(features[j])) return {-1, 0.0};
    scaled[j] = (features[j] - MEANS[j]) / SCALES[j];
    if (!std::isfinite(scaled[j])) return {-1, 0.0};
  }
  double best[K];
  int nearest[K];
  for (int k = 0; k < K; ++k) {
    best[k] = std::numeric_limits<double>::infinity();
    nearest[k] = -1;
  }
  // Scan in original reference order. Strict < retains lower index on ties,
  // matching Python's sorting by (distance, reference index).
  for (int i = 0; i < REFERENCE_COUNT; ++i) {
    double distance = 0.0;
    for (int j = 0; j < 4; ++j) {
      const double difference = scaled[j] - REFERENCES[i][j];
      distance += difference * difference;
    }
    if (!std::isfinite(distance)) return {-1, 0.0};
    for (int k = 0; k < K; ++k) {
      if (distance < best[k]) {
        for (int next = K - 1; next > k; --next) {
          best[next] = best[next - 1]; nearest[next] = nearest[next - 1];
        }
        best[k] = distance; nearest[k] = i;
        break;
      }
    }
  }
  int votes[3] = {0, 0, 0};
  for (int k = 0; k < K; ++k) {
    if (nearest[k] < 0) return {-1, 0.0};
    ++votes[LABELS[nearest[k]]];
  }
  int winner = 0;
  for (int c = 1; c < 3; ++c) if (votes[c] > votes[winner]) winner = c;
  return {winner, static_cast<double>(votes[winner]) / K};
}

// One history per segment. Timestamps are DOUBLE seconds, never float epoch
// seconds (float cannot preserve measurement timing at current epoch values).
class History {
  double times_[WINDOW];
  double deltas_[WINDOW];
  int count_ = 0;
 public:
  void reset() { count_ = 0; }
  bool update(double delta, double timestamp, double out[4]) {
    if (!std::isfinite(delta) || !std::isfinite(timestamp)) { reset(); return false; }
    if (count_ && timestamp <= times_[count_ - 1]) return false;
    if (count_ && timestamp - times_[count_ - 1] > STALE_SECONDS) reset();
    if (count_ == WINDOW) {
      for (int i = 1; i < WINDOW; ++i) {
        times_[i-1] = times_[i]; deltas_[i-1] = deltas_[i];
      }
      --count_;
    }
    times_[count_] = timestamp; deltas_[count_++] = delta;
    if (count_ < WINDOW) return false;
    double mean = 0.0, variance = 0.0, volume = 0.0;
    for (int i = 0; i < WINDOW; ++i) mean += deltas_[i] / WINDOW;
    for (int i = 0; i < WINDOW; ++i) {
      const double difference = deltas_[i] - mean;
      variance += difference * difference / WINDOW;
      if (i) volume += deltas_[i] * (times_[i] - times_[i-1]) / 60.0;
    }
    out[0] = delta;
    out[1] = (deltas_[WINDOW-1] - deltas_[WINDOW-2]) /
             (times_[WINDOW-1] - times_[WINDOW-2]);
    out[2] = variance; out[3] = volume;
    return true;
  }
};

struct CycleResult {
  Prediction segment[2];
  double features[2][4];
  double loss_percent[2];
  const char* overall;
  const char* data_quality;
  bool review_inlet;
  bool review_severity[2];
};

// Pass ONE complete cycle in node order: inlet, midpoint, outlet.
// The firmware must collect all three measurements before calling update().
// This class rejects duplicates rather than reusing readings across cycles.
class Pipeline {
  History history_[2];
  double last_[3] = {0, 0, 0};
  bool has_last_ = false;
 public:
  void reset() { history_[0].reset(); history_[1].reset(); has_last_ = false; }
  CycleResult update(const double q[3], const double timestamps[3], double now,
                     const bool sensor_ok[3]) {
    CycleResult result = {};
    result.segment[0] = {-1, 0.0}; result.segment[1] = {-1, 0.0};
    result.overall = "INFERENCE_UNAVAILABLE";
    result.data_quality = "INVALID_PAYLOAD";
    if (!std::isfinite(now)) return result;
    double earliest = timestamps[0], latest = timestamps[0];
    for (int i = 0; i < 3; ++i) {
      if (!std::isfinite(q[i]) || !std::isfinite(timestamps[i])) { reset(); return result; }
      if (!sensor_ok[i] || q[i] < MIN_VALID_FLOW || q[i] > MAX_VALID_FLOW) {
        history_[0].reset(); history_[1].reset();
        result.data_quality = "SENSOR_FAULT_OR_FLOW_OUT_OF_RANGE"; return result;
      }
      if (now - timestamps[i] > STALE_SECONDS || timestamps[i] - now > TOLERANCE_SECONDS) {
        result.data_quality = "STALE_OR_FUTURE_DATA"; return result;
      }
      if (has_last_ && timestamps[i] <= last_[i]) {
        result.data_quality = "DUPLICATE_OR_OUT_OF_ORDER"; return result;
      }
      if (timestamps[i] < earliest) earliest = timestamps[i];
      if (timestamps[i] > latest) latest = timestamps[i];
    }
    if (latest - earliest > TOLERANCE_SECONDS) {
      result.data_quality = "UNSYNCHRONIZED_DATA"; return result;
    }
    for (int i = 0; i < 3; ++i) last_[i] = timestamps[i];
    has_last_ = true;
    bool ready1 = history_[0].update(q[0]-q[1], latest, result.features[0]);
    bool ready2 = history_[1].update(q[1]-q[2], latest, result.features[1]);
    if (!ready1 || !ready2) { result.data_quality = "WARMING_UP"; return result; }
    result.review_inlet = q[0] < MIN_INLET_FLOW || q[0] > MAX_INLET_FLOW;
    bool review = result.review_inlet;
    for (int s = 0; s < 2; ++s) {
      result.segment[s] = predict(result.features[s]);
      if (result.segment[s].class_id < 0) return result;
      result.loss_percent[s] = 100.0 * (q[s]-q[s+1]) / q[s];
      result.review_severity[s] = result.loss_percent[s] > 15 && result.loss_percent[s] < 25;
      review = review || result.review_severity[s];
    }
    int a = result.segment[0].class_id, b = result.segment[1].class_id;
    result.overall = a > 0 && b > 0 ? "CRITICAL" : a == 2 || b == 2 ? "MAJOR LEAK" :
                     a == 1 || b == 1 ? "MINOR LEAK" : "NORMAL";
    result.data_quality = review ? "REVIEW_REQUIRED" : "OK";
    return result;
  }
};
} // namespace flow_model
#endif
